### ISSUE TITLE
Console error when no warriors are loaded and the core is reset

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar-ui#287]
Write a warrior, run it for a bit, pause.

Remove the warrior so no warriors exist. Click 'reset' and a console error occurs:

```
uncaught at rootSaga at rootSaga 
 at takeLatest 
 at initSaga 
 at initialiseCore 
 TypeError: Cannot read property 'tasks' of undefined
    at Fetcher.isDead (http://localhost:3000/static/js/bundle.js:6689:24)
    at Fetcher.getNextFetchContext (http://localhost:3000/static/js/bundle.js:6650:21)
    at Fetcher.getNextExecution (http://localhost:3000/static/js/bundle.js:6664:28)
    at Simulator.publishNextExecution (http://localhost:3000/static/js/bundle.js:6737:35)
    at Simulator.initialise (http://localhost:3000/static/js/bundle.js:6749:14)
    at Api.initialiseSimulator (http://localhost:3000/static/js/bundle.js:1937:24)
    at runCallEffect (http://localhost:3000/static/js/bundle.js:60408:19)
    at runEffect (http://localhost:3000/static/js/bundle.js:60330:648)
    at next (http://localhost:3000/static/js/bundle.js:60210:9)
    at currCb (http://localhost:3000/static/js/bundle.js:60283:7)
    at runCallEffect (http://localhost:3000/static/js/bundle.js:60412:229)
    at runEffect (http://localhost:3000/static/js/bundle.js:60330:648)
    at next (http://localhost:3000/static/js/bundle.js:60210:9)
    at proc (http://localhost:3000/static/js/bundle.js:60165:3)
    at resolveIterator (http://localhost:3000/static/js/bundle.js:60351:5)
    at runCallEffect (http://localhost:3000/static/js/bundle.js:60412:180)
    at runEffect (http://localhost:3000/static/js/bundle.js:60330:648)
    at next (http://localhost:3000/static/js/bundle.js:60210:9)
    at Object.currCb [as cont] (http://localhost:3000/static/js/bundle.js:60283:7)
    at end (http://localhost:3000/static/js/bundle.js:60251:23)
    at Object.task.cont (http://localhost:3000/static/js/bundle.js:59994:11)
    at next (http://localhost:3000/static/js/bundle.js:60216:35)
    at currCb (http://localhost:3000/static/js/bundle.js:60283:7)
    at runSelectEffect (http://localhost:3000/static/js/bundle.js:60594:7)
    at runEffect (http://localhost:3000/static/js/bundle.js:60330:1212)
    at next (http://localhost:3000/static/js/bundle.js:60210:9)
    at currCb (http://localhost:3000/static/js/bundle.js:60283:7)
    at runSelectEffect (http://localhost:3000/static/js/bundle.js:60594:7)
    at runEffect (http://localhost:3000/static/js/bundle.js:60330:1212)
    at next (http://localhost:3000/static/js/bundle.js:60210:9)
    at proc (http://localhost:3000/static/js/bundle.js:60165:3)
    at resolveIterator (http://localhost:3000/static/js/bundle.js:60351:5)
    at runCallEffect (http://localhost:3000/static/js/bundle.js:60412:180)
    at runEffect (http://localhost:3000/static/js/bundle.js:60330:648)
    at next (http://localhost:3000/static/js/bundle.js:60210:9)
    at currCb (http://localhost:3000/static/js/bundle.js:60283:7)
    at http://localhost:3000/static/js/bundle.js:60394:16
    at exec (http://localhost:3000/static/js/bundle.js:61024:5)
    at flush (http://localhost:3000/static/js/bundle.js:61065:5)
    at asap (http://localhost:3000/static/js/bundle.js:61038:5)
    at Array.<anonymous> (http://localhost:3000/static/js/bundle.js:59452:71)
    at Object.emit (http://localhost:3000/static/js/bundle.js:59293:13)
    at http://localhost:3000/static/js/bundle.js:59858:21
    at http://localhost:3000/static/js/bundle.js:61498:12
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:32094:14)
    at HTMLUnknownElement.t._rollbar_wrapped.t._rollbar_wrapped (https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.3.1/rollbar.min.js:1:5022)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:32133:16)
    at Object.invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:31990:27)
    at Object.invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:32004:43)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:32388:19)
__stack_frame_overlay_proxy_console__ @ index.js:2178
n.(anonymous function) @ rollbar.min.js:2
log @ utils.js:225
logError @ proc.js:210
end @ proc.js:349
abort @ proc.js:79
task.cont @ proc.js:92
end @ proc.js:356
abort @ proc.js:79
task.cont @ proc.js:92
end @ proc.js:356
abort @ proc.js:79
task.cont @ proc.js:92
next @ proc.js:328
currCb @ proc.js:388
end @ proc.js:356
abort @ proc.js:79
task.cont @ proc.js:92
next @ proc.js:328
currCb @ proc.js:388
runCallEffect @ proc.js:515
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
proc @ proc.js:270
resolveIterator @ proc.js:456
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
end @ proc.js:356
task.cont @ proc.js:99
next @ proc.js:321
currCb @ proc.js:388
runSelectEffect @ proc.js:699
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
runSelectEffect @ proc.js:699
runEffect @ proc.js:435
next @ proc.js:315
proc @ proc.js:270
resolveIterator @ proc.js:456
runCallEffect @ proc.js:517
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
(anonymous) @ bindActionCreators.js:3
callCallback @ react-dom.development.js:542
t._rollbar_wrapped.t._rollbar_wrapped @ rollbar.min.js:1
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:452
executeDispatch @ react-dom.development.js:836
executeDispatchesInOrder @ react-dom.development.js:858
executeDispatchesAndRelease @ react-dom.development.js:956
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:967
forEachAccumulated @ react-dom.development.js:935
processEventQueue @ react-dom.development.js:1112
runEventQueueInBatch @ react-dom.development.js:3607
handleTopLevel @ react-dom.development.js:3616
handleTopLevelImpl @ react-dom.development.js:3347
batchedUpdates @ react-dom.development.js:11082
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
r._rollbar_wrapped.r._rollbar_wrapped @ src:47
```

**Comment by dougajmcdonald** [comment]
This is the same as #300, fixed by #303
